name:                idream
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/ejconlon/idream#README.md
license:             BSD3
author:              ejconlon
maintainer:          ejconlon
copyright:           ejconlon, 2017
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.5.10.2 && < 0.6
  - bytestring >= 0.10.8.2 && < 0.11
  - data-default >= 0.7.1.1 && < 0.8
  - directory >= 1.3.0.2 && < 1.4
  - text >= 1.2.2.2 && < 1.3
  - aeson >= 1.2.3.0 && < 1.3
  - optparse-applicative >= 0.14.0.0 && < 0.15

executables:
  idream:
    source-dirs:      src
    main:             Main.hs
