name:                idream
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/ejconlon/idream#README.md
license:             BSD3
author:              ejconlon
maintainer:          ejconlon
copyright:           ejconlon, 2017
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.5.10.2 && < 0.6
  - text >= 1.2.2.2 && < 1.3
  - aeson >= 1.2.3.0 && < 1.3

executables:
  idream:
    source-dirs:      src
    main:             Main.hs
