name:                idream
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/ejconlon/idream#README.md
license:             BSD3
author:              idream team
maintainer:          idream team
copyright:           idream team, 2017
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.5.10.2 && < 0.6
  - freer-simple >= 1.1.0.0 && < 2
  - mtl >= 2.2.1 && < 2.3
  - bytestring >= 0.10.8.2 && < 0.11
  - algebraic-graphs >= 0.0.5 && < 1
  - data-default >= 0.7.1.1 && < 0.8
  - filepath >= 1.4.1.2 && < 1.5
  - directory >= 1.3.0.2 && < 1.4
  - shelly >= 1.7.0 && < 1.8
  - text >= 1.2.2.2 && < 1.3
  - aeson >= 1.2.3.0 && < 1.3
  - aeson-pretty >= 0.8.5 && < 1.0
  - optparse-applicative >= 0.14.0.0 && < 0.15
  - process >= 1.6.1.0 && < 1.7

ghc-options: -Wall -Werror -optP-Wno-nonportable-include-path  # -O2

default-extensions:
  - OverloadedStrings
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - GADTs
  - DataKinds
  - TypeOperators
  - ScopedTypeVariables

library:
  source-dirs:    lib

executables:
  idream:
    source-dirs:  src
    main:         Main.hs
    dependencies:
      - idream

tests:
  idream-test:
    main:         test.hs
    source-dirs:  test
    dependencies:
      - idream
      - tasty >= 1.0.1.1 && < 1.1
      - tasty-hspec >= 1.1.3.2 && < 1.2
      - tasty-auto >= 0.2.0.0 && < 0.3
